# This file is used to configure the database connection information.

# Database Configuration.
Database:
  host: "localhost"
  port: 3306
  user: "budgetbee"
  password: "budgetBEE123"
  database: "budget_bee"
  charset: "utf8mb4"

# Build Configuration.
Build:
  name: "Budget Bee"
  template_path: "src/app/templates"
  static_path: "src/app/static"

# Runtime Configuration.
Runtime:
  host: "localhost"
  port: 5000

# Email Configuration.
Email:
  smtp: "smtp.163.com"
  port: 465
  sendername: "Budget Bee Administrator"
  senderemail: "Budg3tB33@163.com"
  senderpassword: "GYbbMZS3vh2iFEpA"